//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuscatShadeOman.Models.DbModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MuscatShadeEntitiesNew : DbContext
    {
        public MuscatShadeEntitiesNew()
            : base("name=MuscatShadeEntitiesNew")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GalleryImage> GalleryImages { get; set; }
        public virtual DbSet<GalleryImageDetail> GalleryImageDetails { get; set; }
        public virtual DbSet<ProjectImageDetail> ProjectImageDetails { get; set; }
        public virtual DbSet<ProjectImage> ProjectImages { get; set; }
    }
}
